
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myweb?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: xfsy2017
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: 9090